name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Test - Database Connection
        run: cd backend && npm test -- --testPathPattern="connection.test.js"
        env:
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET || 'test_jwt_secret_for_github_actions' }}

      - name: Test - Utility Functions
        run: cd backend && npm test -- --testPathPattern="utils.test.js"
        env:
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET || 'test_jwt_secret_for_github_actions' }}

      - name: Test - Authentication
        run: cd backend && npm test -- --testPathPattern="auth.test.js"
        env:
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET || 'test_jwt_secret_for_github_actions' }}

      - name: Test - Task API
        run: cd backend && npm test -- --testPathPattern="tasks.test.js"
        env:
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET || 'test_jwt_secret_for_github_actions' }}

      - name: Install production dependencies
        run: |
          cd backend
          npm ci --omit=dev

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taskmanager-api-prod-ocwrlppzw2f4s'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './backend'
